version: "3.3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "81:80"
        depends_on: 
            - database
    database:
        image: postgres:12
        environment:
            POSTGRES_DB: todo-api
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        ports:
            - "5432:5432"
