version: "3.3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "81:80"
        command: bash -c "composer install && apache2-foreground"